import {
  Link,
  Table,
  TableCaption,
  Td,
  Th,
  Thead,
  Tr,
  Tbody,
} from "@chakra-ui/react";
import React from "react";

const DataTable = ({ queryResults }) => {
  return (
    <Table variant="simple" size="sm">
      <TableCaption>
        Search results generated by frequency and location metrics
      </TableCaption>
      <Thead>
        <Tr>
          <Th>Link</Th>
          <Th isNumeric>Score</Th>
          <Th isNumeric>Content</Th>
          <Th isNumeric>Location</Th>
        </Tr>
      </Thead>
      <Tbody>
        {queryResults.length === 0 ? (
          <Tr></Tr>
        ) : (
          queryResults.map((result) => (
            <Tr key={result.page_url}>
              <Td>
                <Link to={result.page_url}>{result.page_name}</Link>
              </Td>
              <Td isNumeric>{Math.round((result.page_score + Number.EPSILON) * 1000) / 1000}</Td>
              <Td isNumeric>{Math.round((result.freq_score + Number.EPSILON) * 1000) / 1000}</Td>
              <Td isNumeric>{Math.round((result.loc_score + Number.EPSILON) * 1000) / 1000}</Td>
            </Tr>
          ))
        )}
      </Tbody>
    </Table>
  );
};

export default DataTable;
